version: "3"
services:
  elastic-agent:
    image: elastic/elastic-agent:8.6.1
    container_name: elastic-agent
    restart: always
    user: root # note, synthetic browser monitors require this set to `elastic-agent`
    environment:
      - FLEET_SERVER_ENABLE=true
      - FLEET_SERVER_ELASTICSEARCH_HOST=http://10.0.0.101:9200
      - FLEET_SERVER_SERVICE_TOKEN=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NjAyNDcyNTA2MzM6ajJZLTczMkhRY21XaWQxbG1KYVEzUQ
    ports:
      - "8220:8220"
