version: '3'

services:
  jenkins:
    build: .
    image: jenkins/jenkins:lts-jdk11
    privileged: true
    user: root
    volumes:
     - ./vol/conf:/var/jenkins_home
    ports:
     - 8080:8080
     - 50001:50001